GET http://localhost:3000

###

POST http://localhost:3000
Content-Type: application/json
Accept: application/json

{
    "todo": "1234123412341234"
}

###

PUT http://localhost:3000
Content-Type: application/json
Accept: application/json

{
    "id" : 2,
    "todo": "test ganti"
}

###

DELETE http://localhost:3000
Content-Type: application/json
Accept: application/json

{
    "id" : 0
}